import { build } from "esbuild";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = dirname(fileURLToPath(import.meta.url));

await build({
  entryPoints: [join(root, "src", "main.js")],
  outfile: join(root, "main.js"),
  bundle: true,
  external: ["obsidian", "electron"],
  platform: "node",
  format: "cjs",
  target: "node18",
  sourcemap: false,
  minify: true,
  legalComments: "none",
  banner: {
    js: "// Generated by esbuild from src/main.js. Do not edit this file directly.",
  },
  logLevel: "info",
});
